begin;
create table public.reliable_study_protocols (id text,version integer,stage text,document jsonb,sha256 text,locked_at timestamptz,primary key(id),check(version>0));
create table public.reliable_study_campaigns (id text,protocol_id text,title text,stage text,status text,planned_runs integer,recorded_runs integer,experiment_type text,elapsed_seconds numeric,limitations jsonb,provenance jsonb,usage jsonb,primary key(id),foreign key(protocol_id) references reliable_study_protocols(id),check(status in ('complete','failed','partial','excluded','invalid')),check(recorded_runs between 0 and planned_runs));
create table public.reliable_study_configurations (id text,campaign_id text,algorithm text,skewness numeric,budget_bytes integer,budget_regime text,input_sha256 text,details jsonb,requested_resources jsonb,actual_resources jsonb,primary key(id),unique(campaign_id,id),foreign key(campaign_id) references reliable_study_campaigns(id),check(budget_bytes>0));
create table public.reliable_study_runs (id text,campaign_id text,configuration_id text,protocol_id text,stage text,status text,reason text,algorithm text,seed integer,input_sha256 text,raw_sha256 text,analysis_sha256 text,analysis_version text,started_at timestamptz,ended_at timestamptz,measurements jsonb,primary key(id),foreign key(campaign_id,configuration_id) references reliable_study_configurations(campaign_id,id),foreign key(protocol_id) references reliable_study_protocols(id),check(status in ('complete','failed','partial','excluded','invalid')),check(status='complete' or reason is not null));
create table public.reliable_study_measurements (run_id text,metric text,value numeric,status text,reason text,units text,primary key(run_id,metric),foreign key(run_id) references reliable_study_runs(id),check(status in ('recorded','missing','invalid','ambiguous','excluded')),check((status='recorded' and value is not null) or (status<>'recorded' and value is null and reason is not null)));
create table public.reliable_study_summaries (configuration_id text,campaign_id text,planned integer,recorded integer,failed integer,excluded integer,statistics jsonb,interval_kind text,observed_keys integer,query_population text,zero_outlier_runs integer,lossless_runs integer,interval_valid_runs integer,primary key(configuration_id),foreign key(campaign_id,configuration_id) references reliable_study_configurations(campaign_id,id),check(recorded+failed+excluded=planned));
create table public.reliable_study_sources (reference_number integer,citation text,doi text,kind text,role text,source_url text,retrieved_url text,access_status text,review_status text,retrieved_version text,sha256 text,byte_count bigint,pages integer,findings text,limitations text,retrieval_attempts jsonb,reviewer jsonb,primary key(reference_number),check(reference_number between 0 and 46),check(review_status in ('complete','partial','unreviewed','unavailable')));
create table public.reliable_study_claims (id text,location text,description text,assessment text,evidence text,limitation text,proposed_check text,required_inputs text,feasibility text,primary key(id),check(assessment in ('reproduced','discrepant','inconclusive','untested')));
create table public.reliable_study_published (id text,source_number integer,location text,metric text,values jsonb,units text,primary key(id),foreign key(source_number) references reliable_study_sources(reference_number));
create table public.reliable_study_controls (id text,protocol_id text,stage text,payload jsonb,primary key(id),foreign key(protocol_id) references reliable_study_protocols(id));
create table public.reliable_study_control_runs (id text,control_id text,implementation text,seed integer,key integer,weight integer,status text,reason text,raw_sha256 text,payload jsonb,primary key(id),foreign key(control_id) references reliable_study_controls(id),check(status in ('complete','failed','excluded','invalid')),check(status='complete' or reason is not null));
create table public.reliable_study_meta (id text,analysis_version text,assessment_sha256 text,review_definition text,label_definitions jsonb,validation jsonb,counts jsonb,provenance jsonb,costs jsonb,primary key(id));
create table public.reliable_study_artifacts (id text,sha256 text,byte_count bigint,manifest jsonb,storage_path text,payload jsonb,primary key(id),check(byte_count>=0));
create index reliable_measurement_run on reliable_study_measurements(run_id);
create index reliable_runs_configuration on reliable_study_runs(configuration_id,seed);
alter table public.reliable_study_protocols enable row level security;
revoke all on public.reliable_study_protocols from anon,authenticated;
grant all on public.reliable_study_protocols to service_role;
grant select on public.reliable_study_protocols to anon,authenticated;
create policy reliable_public_read on public.reliable_study_protocols for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_protocols;
create policy reliable_deny_browser_writes on public.reliable_study_protocols as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_campaigns enable row level security;
revoke all on public.reliable_study_campaigns from anon,authenticated;
grant all on public.reliable_study_campaigns to service_role;
grant select on public.reliable_study_campaigns to anon,authenticated;
create policy reliable_public_read on public.reliable_study_campaigns for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_campaigns;
create policy reliable_deny_browser_writes on public.reliable_study_campaigns as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_configurations enable row level security;
revoke all on public.reliable_study_configurations from anon,authenticated;
grant all on public.reliable_study_configurations to service_role;
grant select on public.reliable_study_configurations to anon,authenticated;
create policy reliable_public_read on public.reliable_study_configurations for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_configurations;
create policy reliable_deny_browser_writes on public.reliable_study_configurations as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_runs enable row level security;
revoke all on public.reliable_study_runs from anon,authenticated;
grant all on public.reliable_study_runs to service_role;
grant select on public.reliable_study_runs to anon,authenticated;
create policy reliable_public_read on public.reliable_study_runs for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_runs;
create policy reliable_deny_browser_writes on public.reliable_study_runs as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_measurements enable row level security;
revoke all on public.reliable_study_measurements from anon,authenticated;
grant all on public.reliable_study_measurements to service_role;
grant select on public.reliable_study_measurements to anon,authenticated;
create policy reliable_public_read on public.reliable_study_measurements for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_measurements;
create policy reliable_deny_browser_writes on public.reliable_study_measurements as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_summaries enable row level security;
revoke all on public.reliable_study_summaries from anon,authenticated;
grant all on public.reliable_study_summaries to service_role;
grant select on public.reliable_study_summaries to anon,authenticated;
create policy reliable_public_read on public.reliable_study_summaries for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_summaries;
create policy reliable_deny_browser_writes on public.reliable_study_summaries as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_sources enable row level security;
revoke all on public.reliable_study_sources from anon,authenticated;
grant all on public.reliable_study_sources to service_role;
grant select on public.reliable_study_sources to anon,authenticated;
create policy reliable_public_read on public.reliable_study_sources for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_sources;
create policy reliable_deny_browser_writes on public.reliable_study_sources as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_claims enable row level security;
revoke all on public.reliable_study_claims from anon,authenticated;
grant all on public.reliable_study_claims to service_role;
grant select on public.reliable_study_claims to anon,authenticated;
create policy reliable_public_read on public.reliable_study_claims for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_claims;
create policy reliable_deny_browser_writes on public.reliable_study_claims as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_published enable row level security;
revoke all on public.reliable_study_published from anon,authenticated;
grant all on public.reliable_study_published to service_role;
grant select on public.reliable_study_published to anon,authenticated;
create policy reliable_public_read on public.reliable_study_published for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_published;
create policy reliable_deny_browser_writes on public.reliable_study_published as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_controls enable row level security;
revoke all on public.reliable_study_controls from anon,authenticated;
grant all on public.reliable_study_controls to service_role;
grant select on public.reliable_study_controls to anon,authenticated;
create policy reliable_public_read on public.reliable_study_controls for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_controls;
create policy reliable_deny_browser_writes on public.reliable_study_controls as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_control_runs enable row level security;
revoke all on public.reliable_study_control_runs from anon,authenticated;
grant all on public.reliable_study_control_runs to service_role;
grant select on public.reliable_study_control_runs to anon,authenticated;
create policy reliable_public_read on public.reliable_study_control_runs for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_control_runs;
create policy reliable_deny_browser_writes on public.reliable_study_control_runs as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_meta enable row level security;
revoke all on public.reliable_study_meta from anon,authenticated;
grant all on public.reliable_study_meta to service_role;
grant select on public.reliable_study_meta to anon,authenticated;
create policy reliable_public_read on public.reliable_study_meta for select to anon,authenticated using(true);
drop policy if exists jumpserve_require_signed_in_user on public.reliable_study_meta;
create policy reliable_deny_browser_writes on public.reliable_study_meta as restrictive for all to anon,authenticated using(true) with check(false);
alter table public.reliable_study_artifacts enable row level security;
revoke all on public.reliable_study_artifacts from anon,authenticated;
grant all on public.reliable_study_artifacts to service_role;
alter table public.agent_prompt_versions drop constraint agent_prompt_versions_module_id_check;
alter table public.agent_prompt_versions add constraint agent_prompt_versions_module_id_check check(module_id in ('congestion-control-emulated','congestion-control-real-world','leo-emergency-failover','http2-compliance-study','reliable-sketch-study'));
alter table public.agent_prompt_settings drop constraint agent_prompt_settings_module_id_check;
alter table public.agent_prompt_settings add constraint agent_prompt_settings_module_id_check check(module_id in ('congestion-control-emulated','congestion-control-real-world','leo-emergency-failover','http2-compliance-study','reliable-sketch-study'));
alter table public.agent_sessions drop constraint agent_sessions_module_id_check;
alter table public.agent_sessions add constraint agent_sessions_module_id_check check(module_id in ('congestion-control-emulated','congestion-control-real-world','leo-emergency-failover','http2-compliance-study','reliable-sketch-study'));
insert into agent_prompt_settings(module_id) values('reliable-sketch-study') on conflict(module_id) do nothing;
insert into storage.buckets(id,name,public) values('reliable-study-raw','reliable-study-raw',false) on conflict(id) do nothing;
create policy reliable_private_raw on storage.objects as restrictive for all to anon,authenticated using(bucket_id<>'reliable-study-raw') with check(bucket_id<>'reliable-study-raw');
notify pgrst,'reload schema';
commit;
